---
title: "playing_w_data"
author: Emily Schwabe
output: html_document
---


```{r raw_data}
rockfish_larval_data <- read.csv("../data/rsos170639_si_001.csv")
```

#Mini Project: Rockfish Larval Analysis 
This project will compare multiple rockfish larval genusus across a variety of environmental factors such as temperature, oxygen, salinty, year, station and station depth. 




#Required Packages
```{r}
library(dplyr)
help(package = dplyr)
library(ggplot2)
library(tidyr)
```

#Import data in 

#select column by name 

```{r}
rockfish_data_reduced <- select(rockfish_larval_data, year, line, station, station.depth, temp_surf, sal_surf, oxygen_surf, auriculatus, aurora,	caurinus,	chlorostictus,	constellatus,crameri,	crocotulus,	dalli,	did.not.work,	diploproa,	elongatus,	ensifer,	entomelas,	flavidus,	gilli,	goodei, helvomaculatus,	hopkinsi,	jordani,	levis,	macdonaldi,	melanostomus,	miniatus,	moseri,	mystinus,	ovalis,	paucispinis)
```


```{r}
rockfish_data_added_genus <- rockfish_data_reduced %>%
  gather('auriculatus', 'aurora',	'caurinus',	'chlorostictus',	'constellatus', 'crameri',	'crocotulus',	'dalli',	'did.not.work',	'diploproa',	'elongatus',	'ensifer',	'entomelas',	'flavidus',	'gilli',	'goodei', 'helvomaculatus',	'hopkinsi',	'jordani',	'levis',	'macdonaldi',	'melanostomus',	'miniatus',	'moseri',	'mystinus',	'ovalis',	'paucispinis', key = "genus", value = "counts")
```


```{r}
ggplot(rockfish_data_added_genus, aes(x=temp_surf)) +
   geom_histogram(fill="blue", alpha = 0.3) +
   labs(x = "Temp (C)") +
   facet_wrap(~genus)
```


```{r}
ggplot(rockfish_data_added_genus, aes(x = sal_surf, y = counts, color=genus)) +
  geom_point() +
  labs(x = "salinity level at surface" , y = "fish counts", 
       title = "Salinty Affect on Fish Count")
```



## Rockfish Larval Abundance and Environmental Conditions 



